/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tsushi' at '16/08/24 16:54' with Gradle 2.13
 *
 * @author tsushi, @date 16/08/24 16:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
