import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import java.util.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'tsushi' at '16/08/24 16:54' with Gradle 2.13
 *
 * @author tsushi, @date 16/08/24 16:54
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void testMockitLibrary() {
    	List mockedList = mock(List.class);
    	mockedList.add("one");
    	mockedList.clear();
    	
    }
}
